name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install D++ Library
      run: |
        wget https://dl.dpp.dev/latest -O dpp.deb
        sudo apt update
        sudo apt install -y libopus0 libopus-dev
        sudo dpkg -i dpp.deb || sudo apt install -f -y

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
